# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jasoncluck/code/jsrender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jasoncluck/code/jsrender

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jasoncluck/code/jsrender/CMakeFiles /Users/jasoncluck/code/jsrender//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jasoncluck/code/jsrender/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyApp

# Build rule for target.
MyApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyApp
.PHONY : MyApp

# fast build rule for target.
MyApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/build
.PHONY : MyApp/fast

#=============================================================================
# Target rules for targets named qjs

# Build rule for target.
qjs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs
.PHONY : qjs

# fast build rule for target.
qjs/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/qjs.dir/build.make deps/quickjs/CMakeFiles/qjs.dir/build
.PHONY : qjs/fast

#=============================================================================
# Target rules for targets named qjs-libc

# Build rule for target.
qjs-libc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-libc
.PHONY : qjs-libc

# fast build rule for target.
qjs-libc/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/qjs-libc.dir/build.make deps/quickjs/CMakeFiles/qjs-libc.dir/build
.PHONY : qjs-libc/fast

#=============================================================================
# Target rules for targets named qjsc

# Build rule for target.
qjsc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjsc
.PHONY : qjsc

# fast build rule for target.
qjsc/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/qjsc.dir/build.make deps/quickjs/CMakeFiles/qjsc.dir/build
.PHONY : qjsc/fast

#=============================================================================
# Target rules for targets named qjs_exe

# Build rule for target.
qjs_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs_exe
.PHONY : qjs_exe

# fast build rule for target.
qjs_exe/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/qjs_exe.dir/build.make deps/quickjs/CMakeFiles/qjs_exe.dir/build
.PHONY : qjs_exe/fast

#=============================================================================
# Target rules for targets named run-test262

# Build rule for target.
run-test262: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run-test262
.PHONY : run-test262

# fast build rule for target.
run-test262/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/run-test262.dir/build.make deps/quickjs/CMakeFiles/run-test262.dir/build
.PHONY : run-test262/fast

#=============================================================================
# Target rules for targets named api-test

# Build rule for target.
api-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 api-test
.PHONY : api-test

# fast build rule for target.
api-test/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/api-test.dir/build.make deps/quickjs/CMakeFiles/api-test.dir/build
.PHONY : api-test/fast

#=============================================================================
# Target rules for targets named lre-test

# Build rule for target.
lre-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lre-test
.PHONY : lre-test

# fast build rule for target.
lre-test/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/lre-test.dir/build.make deps/quickjs/CMakeFiles/lre-test.dir/build
.PHONY : lre-test/fast

#=============================================================================
# Target rules for targets named unicode_gen

# Build rule for target.
unicode_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unicode_gen
.PHONY : unicode_gen

# fast build rule for target.
unicode_gen/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/unicode_gen.dir/build.make deps/quickjs/CMakeFiles/unicode_gen.dir/build
.PHONY : unicode_gen/fast

#=============================================================================
# Target rules for targets named function_source

# Build rule for target.
function_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function_source
.PHONY : function_source

# fast build rule for target.
function_source/fast:
	$(MAKE) $(MAKESILENT) -f deps/quickjs/CMakeFiles/function_source.dir/build.make deps/quickjs/CMakeFiles/function_source.dir/build
.PHONY : function_source/fast

src/JSBridge.o: src/JSBridge.cpp.o
.PHONY : src/JSBridge.o

# target to build an object file
src/JSBridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/JSBridge.cpp.o
.PHONY : src/JSBridge.cpp.o

src/JSBridge.i: src/JSBridge.cpp.i
.PHONY : src/JSBridge.i

# target to preprocess a source file
src/JSBridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/JSBridge.cpp.i
.PHONY : src/JSBridge.cpp.i

src/JSBridge.s: src/JSBridge.cpp.s
.PHONY : src/JSBridge.s

# target to generate assembly for a file
src/JSBridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/JSBridge.cpp.s
.PHONY : src/JSBridge.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MyApp"
	@echo "... api-test"
	@echo "... function_source"
	@echo "... lre-test"
	@echo "... qjs"
	@echo "... qjs-libc"
	@echo "... qjs_exe"
	@echo "... qjsc"
	@echo "... run-test262"
	@echo "... unicode_gen"
	@echo "... src/JSBridge.o"
	@echo "... src/JSBridge.i"
	@echo "... src/JSBridge.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

